# Generated by Django 5.2 on 2025-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField()),
                ('lime_rating', models.IntegerField(blank=True, null=True)),
                ('shap_rating', models.IntegerField(blank=True, null=True)),
                ('deeplift_rating', models.IntegerField(blank=True, null=True)),
                ('integrated_gradients_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
