# Generated by Django 5.2 on 2025-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxicity_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='deeplift_explanation_goodness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_system_controllability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_user_curiosity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_user_productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_user_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_user_trust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deeplift_user_understanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_explanation_goodness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_system_controllability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_user_curiosity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_user_productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_user_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_user_trust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='integrated_gradients_user_understanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_explanation_goodness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_system_controllability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_user_curiosity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_user_productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_user_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_user_trust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='lime_user_understanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_explanation_goodness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_system_controllability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_user_curiosity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_user_productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_user_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_user_trust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='shap_user_understanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='deeplift_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='integrated_gradients_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='lime_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='shap_rating',
            field=models.IntegerField(default=3),
        ),
    ]
